services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: question_guide
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
